list(
  APPEND
  PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/bar/bar_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/button/button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/card/card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/card/card_header_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/circle_button/circle_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/column/column_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/div/div_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/icon_button/icon_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/roller/roller_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/row/row_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/slider/slider_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/switch/switch_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/table/table_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/alarm/alarm_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/light_temperature/light_temperature_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/speaker_volume/speaker_volume_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/theme_swtcher/theme_switcher_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/elements_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/pubmote_ui_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/pubmote_ui.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/geist_semibold_12_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/geist_semibold_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/geist_bold_16_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/geist_semibold_20_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/geist_semibold_28_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/geist_regular_12_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/geist_regular_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/geist_light_60_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/literata_80_data.c)