list(
  APPEND
  PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/widgets/battery_gauge/battery_gauge.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/battery_gauge/battery_gauge_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/battery_gauge/battery_gauge_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/dynamic_fmt_label/dynamic_fmt_label.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/dynamic_fmt_label/dynamic_fmt_label_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/dynamic_fmt_label/dynamic_fmt_label_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/dynamic_range_arc/dynamic_range_arc.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/dynamic_range_arc/dynamic_range_arc_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/dynamic_range_arc/dynamic_range_arc_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/input_preview/input_preview.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/input_preview/input_preview_xml_parser.c
  ${CMAKE_CURRENT_LIST_DIR}/widgets/input_preview/input_preview_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/bar/bar_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/button/button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/button/button_outlined_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/button/button_primary_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/circle_button/circle_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/div/div_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/footpad_indicator/footpad_indicator_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/icon_button/icon_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/page/body_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/page/footer_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/page/footer_buttons_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/page/header_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/page/page_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/slider/slider_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/speed_gauge/speed_gauge_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/switch/switch_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/text/h1_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/text/label_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/utilization_gauge/utilization_gauge_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/about_screen_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/calibration_screen_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/charge_screen_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/menu_screen_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/pairing_screen_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/settings_screen_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/splash_screen_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/stats_screen_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/update_screen_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/pubmote_ui_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/pubmote_ui.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_12_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_16_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_24_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_28_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_42_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_64_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_72_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_96_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_bold_12_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_bold_14_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_bold_16_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_bold_24_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_bold_28_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_bold_42_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_bold_72_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/inter_bold_96_data.c)