"""Generate a versioned QR matrix using qrcode==8.2 (no image library needed).

Use --preview to regenerate the Slint editor's unversioned PNG (needs Pillow).
"""
import argparse
from pathlib import Path
from urllib.parse import urlencode

import qrcode

BASE_URL = "https://pubmote.com/getting-started/"
ROOT = Path(__file__).resolve().parents[1]

def guide_url(ref):
    return BASE_URL + ("?" + urlencode({"tag": ref}) if ref else "")


def make_qr(ref):
    qr = qrcode.QRCode(error_correction=qrcode.constants.ERROR_CORRECT_M, box_size=1, border=4)
    qr.add_data(guide_url(ref))
    qr.make(fit=True)
    return qr


def generate_header(ref):
    matrix = make_qr(ref).get_matrix()
    # Packed modules including a four-module quiet zone. Expanded once into a
    # Slint pixel buffer during startup, shared by both screens.
    bits = [int(cell) for row in matrix for cell in row]
    data = [sum(bit << (7 - j) for j, bit in enumerate(bits[i:i + 8]))
            for i in range(0, len(bits), 8)]
    return ("// Generated by scripts/generate_guide_qr.py\n#pragma once\n"
            f"static constexpr unsigned GUIDE_QR_SIZE = {len(matrix)};\n"
            "static constexpr unsigned char GUIDE_QR_BITS[] = {\n    "
            + ", ".join(f"0x{byte:02x}" for byte in data) + "\n};\n").encode()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tag", default="")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--preview", action="store_true")
    args = parser.parse_args()
    if args.preview:
        make_qr("").make_image(fill_color="black", back_color="white").save(
            ROOT / "firmware/assets/guide-qr.png")
    elif args.output:
        args.output.write_bytes(generate_header(args.tag))
    else:
        parser.error("specify --output or --preview")
