#!/usr/bin/env python3
"""Point the VS Code Slint extension at our fork's language server.

The extension's bundled slint-lsp is both the compiler and the live preview, so a
stock build rejects `arc-center-x` with "Unknown property" and no preview opens.
The extension's `slint.lspBinaryPath` setting overrides which binary it spawns,
which is why this sets that rather than overwriting anything in the extension -
a VS Code update replaces the extension directory but not your settings.

The release to fetch is not configured here: it comes from the same
SLINT_PREBUILT_REPO / _TAG in platformio.ini that the firmware build uses, so the
preview and the panel can never disagree about which Slint they are on.

The binary lands in .slint/<tag>/ (gitignored) and the setting goes in this repo's
.vscode/settings.json, so the fork's LSP applies here and not to every other Slint
project on the machine.

The value has to be an absolute path - the extension looks a relative one up on PATH
rather than against the workspace - so it is machine specific and cannot be committed.
On someone else's checkout the path does not exist, and the extension then starts no
LSP at all rather than falling back to the bundled one. That is why .vscode/settings.json
is gitignored and regenerated here from the tracked .vscode/settings.shared.json on every
run: the shared editor config stays in the repo, the machine-specific line never enters it.
Anything hand-written in settings.json is overwritten - put it in the template, or in your
VS Code user settings.

Note the preview draws arcs through the MoveTo/ArcTo fallback in the .slint source,
not the fast arc path - only the software renderer implements arc-center-x, and the
desktop preview uses femtovg/skia. It validates shape and layout, never the MCU
rasteriser.

    python scripts/sync_slint_lsp.py                 # fetch and configure
    python scripts/sync_slint_lsp.py --local PATH    # use a local cargo build
    python scripts/sync_slint_lsp.py --print-setting # show it, change nothing
    python scripts/sync_slint_lsp.py --restore       # back to the packaged LSP
"""

import argparse
import json
import platform
import re
import shutil
import stat
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PLATFORMIO_INI = ROOT / "platformio.ini"
SETTING = "slint.lspBinaryPath"

# settings.json is generated from this and gitignored, so the machine-specific path below
# is never in the repo. Shared editor config belongs in the template, not the output.
SHARED_SETTINGS = ROOT / ".vscode" / "settings.shared.json"
GENERATED_HEADER = """\
// Generated by scripts/sync_slint_lsp.py, which the Sync Slint LSP task runs on folder
// open. Rewritten from settings.shared.json every time - edit that instead. Personal
// preferences belong in your VS Code user settings, which this never touches.
"""

# The release names host binaries the way the slint-compiler assets already are.
HOSTS = {
    ("Windows", "AMD64"): ("windows-x86_64", ".exe"),
    ("Windows", "ARM64"): ("windows-aarch64", ".exe"),
    ("Linux", "x86_64"): ("linux-x86_64", ""),
    ("Linux", "aarch64"): ("linux-aarch64", ""),
    ("Darwin", "arm64"): ("macos-aarch64", ""),
    ("Darwin", "x86_64"): ("macos-x86_64", ""),
}

EDITORS = [
    (".vscode", "Code"),
    (".vscode-insiders", "Code - Insiders"),
    (".cursor", "Cursor"),
    (".vscodium", "VSCodium"),
]


def die(msg):
    sys.exit(f"error: {msg}")


def host_key():
    key = (platform.system(), platform.machine())
    if key not in HOSTS:
        die(f"unsupported host {key}. Add it to HOSTS in {Path(__file__).name}.")
    return HOSTS[key]


def find_editor():
    """The installed Slint extension. Only reported, and to fail early if it is missing."""
    found = []
    for dirname, app in EDITORS:
        root = Path.home() / dirname / "extensions"
        if not root.is_dir():
            continue
        for p in root.glob("slint.slint-*"):
            if p.is_dir():
                found.append((p, app))
    if not found:
        die("Slint extension not found. Install it first.")

    def version_of(item):
        try:
            return tuple(int(x) for x in item[0].name.split("-", 1)[1].split("."))
        except (IndexError, ValueError):
            return (0,)

    return max(found, key=version_of)


def read_prebuilt_pin():
    """repo and tag from platformio.ini, the one place the Slint release is pinned."""
    if not PLATFORMIO_INI.exists():
        die(f"{PLATFORMIO_INI} not found")
    text = PLATFORMIO_INI.read_text(encoding="utf-8")
    out = {}
    for key in ("REPO", "TAG", "VERSION"):
        m = re.search(rf"-DSLINT_PREBUILT_{key}=(\S+)", text)
        if m:
            out[key] = m.group(1)
    for key in ("REPO", "TAG"):
        if key not in out:
            die(f"SLINT_PREBUILT_{key} not found in platformio.ini")
    return out["REPO"], out["TAG"], out.get("VERSION", "?")


def cache_dir(tag):
    """Gitignored, and inside the repo so it is obvious what fetched it and where it went.

    Kept per tag so switching branches does not re-download; delete .slint to reclaim the
    space. The setting still has to be the absolute path - the extension treats a relative
    one as a program name to look up on PATH - so this cannot be committed either way.
    """
    return ROOT / ".slint" / tag


def download(url, dest):
    dest.parent.mkdir(parents=True, exist_ok=True)
    print(f"fetching  {url}")
    tmp = dest.with_suffix(dest.suffix + ".part")
    try:
        with urllib.request.urlopen(url) as r, open(tmp, "wb") as f:
            shutil.copyfileobj(r, f)
    except urllib.error.HTTPError as e:
        tmp.unlink(missing_ok=True)
        if e.code == 404:
            die(
                f"no such asset ({url}).\n\n"
                "  Releases cut before the host-binaries job started publishing slint-lsp\n"
                "  only carry slint-compiler. Tag a new mcu-v* release in the fork and\n"
                "  bump SLINT_PREBUILT_TAG in platformio.ini, or point at a local build:\n\n"
                "    cargo build --release -p slint-lsp        (in the fork)\n"
                f"    python scripts/{Path(__file__).name} --local <fork>/target/release/slint-lsp"
            )
        die(f"download failed: {e}")
    tmp.replace(dest)
    dest.chmod(dest.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def prune_cache(keep_tag):
    """Drop cached binaries for tags we are no longer pinned to - 30MB each."""
    root = ROOT / ".slint"
    if not root.is_dir():
        return
    for d in sorted(root.iterdir()):
        if not d.is_dir() or d.name == keep_tag:
            continue
        try:
            shutil.rmtree(d)
            print(f"pruned    {d.name}")
        except OSError:
            # Windows holds a running binary open, and the old LSP usually still is until
            # the window reloads. It goes on the next run.
            print(f"kept      {d.name} (in use - rerun after reloading the window)")


def edit_settings(path, value):
    """Set or remove the key, leaving the rest of the file byte-for-byte alone.

    A surgical text edit rather than json.dump: these files are JSONC and ours has
    comments and a trailing comma that a serialiser would quietly reformat away.
    No backup - the file is in git, so `git restore` is the undo.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    text = path.read_text(encoding="utf-8") if path.exists() else "{\n}\n"

    pattern = re.compile(rf'^([ \t]*)"{re.escape(SETTING)}"\s*:\s*.*?,?\s*$',
                         re.MULTILINE)
    if value is None:
        new, n = pattern.subn("", text)
        if not n:
            return False
        new = re.sub(r"\n{3,}", "\n\n", new)
        path.write_text(re.sub(r"\{\n\s*\n", "{\n", new, count=1), encoding="utf-8")
        return True

    encoded = json.dumps(str(value))
    if pattern.search(text):
        new = pattern.sub(lambda m: f'{m.group(1)}"{SETTING}": {encoded},', text, count=1)
    else:
        brace = text.index("{")
        new = text[: brace + 1] + f'\n    "{SETTING}": {encoded},' + text[brace + 1:]
    path.write_text(new, encoding="utf-8")
    return True


def regenerate_from_shared(path):
    """Overwrite settings.json with the tracked template, ready for the setting to go in.

    Nothing merges: whatever was there is replaced. That is what makes the file safe to
    gitignore - it holds no state anyone can lose. Older checkouts have no template, so
    fall back to editing whatever is already there.
    """
    if not SHARED_SETTINGS.exists():
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(GENERATED_HEADER + SHARED_SETTINGS.read_text(encoding="utf-8"),
                    encoding="utf-8")
    return True


def main():
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo", help="Override SLINT_PREBUILT_REPO")
    ap.add_argument("--tag", help="Override SLINT_PREBUILT_TAG")
    ap.add_argument("--local", help="Use this slint-lsp binary instead of fetching one")
    ap.add_argument("--print-setting", action="store_true",
                    help="Print the setting and change nothing")
    ap.add_argument("--restore", action="store_true",
                    help="Remove the setting, back to the packaged LSP until the next "
                         "folder open re-runs the Sync Slint LSP task")
    ap.add_argument("--force", action="store_true", help="Re-download even if cached")
    args = ap.parse_args()

    ext, app = find_editor()
    settings = ROOT / ".vscode" / "settings.json"

    if args.restore:
        if edit_settings(settings, None):
            print(f"removed {SETTING} from {settings}")
        else:
            print(f"{SETTING} was not set in {settings}")
        print("Run 'Developer: Reload Window'.")
        if (ROOT / ".vscode" / "tasks.json").exists():
            print("\nnote: the Sync Slint LSP task puts it back on the next folder open.")
            print("      Drop the runOptions block from .vscode/tasks.json to stop that.")
        return

    if args.local:
        binary = Path(args.local).resolve()
        if not binary.exists():
            die(f"{binary} does not exist")
    else:
        host, exe = host_key()
        repo, tag, version = read_prebuilt_pin()
        repo, tag = args.repo or repo, args.tag or tag
        print(f"pinned    {repo} @ {tag} (Slint {version})")
        binary = cache_dir(tag) / f"slint-lsp-{host}{exe}"
        if binary.exists() and not args.force:
            print(f"cached    {binary}")
        else:
            download(f"https://github.com/{repo}/releases/download/{tag}/"
                     f"slint-lsp-{host}{exe}", binary)

    print(f"binary    {binary} ({binary.stat().st_size / 1e6:.1f} MB)")
    print(f"editor    {app}, extension {ext.name}")

    if args.print_setting:
        print(f'\n    "{SETTING}": {json.dumps(str(binary))}')
        return

    if regenerate_from_shared(settings):
        print(f"rebuilt   {settings.name} from {SHARED_SETTINGS.name}")
    edit_settings(settings, binary)
    print(f"\nset {SETTING} in {settings}")

    # Only once the setting points at this tag, and only when the tag is ours to reason
    # about - with --local nothing in .slint is current, so there is no safe answer.
    if not args.local:
        prune_cache(binary.parent.name)

    print("Run 'Developer: Reload Window' to pick it up.")
    print(f"Undo with: python scripts/{Path(__file__).name} --restore")


if __name__ == "__main__":
    main()
