import { Theme } from "theme.slint";
import { BatteryIndicator } from "battery-indicator.slint";

export component BatteryDisplay inherits Rectangle {
    in property <int> battery: 100;
    in property <bool> charging: false;
    in property <bool> show-percent: true;

    HorizontalLayout {
        spacing: 6px * Theme.scale;
        if root.show-percent && Theme.panel-width >= 200px : Text {
            text: root.battery + "%";
            color: Theme.text-dim;
            font-size: Theme.font-10;
            font-weight: Theme.w-semibold;
            font-family: "JetBrains Mono";
            vertical-alignment: center;
        }
        VerticalLayout {
            alignment: center;
            BatteryIndicator {
                battery: root.battery;
                charging: root.charging;
            }
        }
    }
}
