import { Theme } from "theme.slint";
import { BatteryIndicator } from "battery-indicator.slint";
import { RssiIndicator } from "rssi-indicator.slint";

export component StatsHeader inherits Rectangle {
    in property <int> remote-battery: 100;
    in property <bool> remote-charging: false;
    in property <bool> is-connected: false;
    in property <int> rssi-bars: 0;
    in property <string> board-state-message: "";

    VerticalLayout {
        width: 100%;
        height: 100%;
        alignment: end;
        
        if root.board-state-message != "" : Text {
            text: root.board-state-message;
            color: Theme.color-warning;
            font-size: Theme.font-14;
            font-weight: Theme.w-bold;
            horizontal-alignment: center;
        }

        if root.board-state-message == "" : HorizontalLayout {
            alignment: center;
            spacing: 6px * Theme.scale;
            
            BatteryIndicator {
                battery: root.remote-battery;
                charging: root.remote-charging;
            }

            if root.is-connected && root.rssi-bars >= 0 : RssiIndicator {
                rssi-bars: root.rssi-bars;
            }
        }
    }
}
